### ISSUE TITLE
RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.

### ISSUE THREAD

**Issue by frankdarkluo** [inseq-team/inseq#263]
## Question

When I load inseq onto a LLM that is loaded onto two  GPUs shown below

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map='auto',
        # load_in_8bit=True,
        cache_dir='/mnt/nvme/xxx/',
        torch_dtype=torch.float16,
    )
    qa_model = inseq.load_model(model, "attention", tokenizer=model_name, tokenizer_kwargs={"legacy": False})``

Then I got the full error as

> Traceback (most recent call last):
  File "/mnt/nvme/xx/inseq/examples/main.py", line 90, in <module>
    qa_model = inseq.load_model(model, "attention", tokenizer=model_name, tokenizer_kwargs={"legacy": False})
  File "/opt/anaconda3/envs/tuned-lens/lib/python3.9/site-packages/inseq/models/__init__.py", line 47, in load_model
    return FRAMEWORKS_MAP[framework].load(model, attribution_method, **kwargs)
  File "/opt/anaconda3/envs/tuned-lens/lib/python3.9/site-packages/inseq/models/huggingface_model.py", line 154, in load
    return HuggingfaceDecoderOnlyModel(
  File "/opt/anaconda3/envs/tuned-lens/lib/python3.9/site-packages/inseq/models/huggingface_model.py", line 482, in __init__
    super().__init__(model, attribution_method, tokenizer, device, model_kwargs, tokenizer_kwargs, **kwargs)
  File "/opt/anaconda3/envs/tuned-lens/lib/python3.9/site-packages/inseq/models/huggingface_model.py", line 132, in __init__
    self.setup(device, attribution_method, **kwargs)
  File "/opt/anaconda3/envs/tuned-lens/lib/python3.9/site-packages/inseq/models/attribution_model.py", line 241, in setup
    self.device = device if device is not None else get_default_device()
  File "/opt/anaconda3/envs/tuned-lens/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in __setattr__
    super().__setattr__(name, value)
  File "/opt/anaconda3/envs/tuned-lens/lib/python3.9/site-packages/inseq/models/huggingface_model.py", line 169, in device
    self.model.to(self._device)
  File "/opt/anaconda3/envs/tuned-lens/lib/python3.9/site-packages/accelerate/big_modeling.py", line 453, in wrapper
    raise RuntimeError("You can't move a model that has some modules offloaded to cpu or disk.")
RuntimeError: You can't move a model that has some modules offloaded to cpu or disk.

How can I solve this problem?

Is there any tutorial or link for possible solution?

## Checklist

- [✅] I've searched the project's [`issues`](https://github.com/inseq-team/inseq/issues?q=is%3Aissue).

**Comment by gsarti** [comment]
Hi! Thanks for reporting this, indeed it seems that the usage with multi-gpu is not working if quantization is not specified due to a bad device casting. Could you try to checkout the branch of PR #264 to see if that works for you?

**Comment by frankdarkluo** [comment]
It is possible that something should be added here? https://github.com/inseq-team/inseq/blob/fix-device-map-multigpu/inseq/models/huggingface_model.py#L170--L172

**Comment by gsarti** [comment]
Hey @frankdarkluo, you're right, the setter is actually the one in the `HuggingfaceModel` class. I applied a fix that should prevent the move to GPU operation in case a device map is specified, could you try it again?

**Comment by frankdarkluo** [comment]
Thanks! I think it is working now!
